name: CI/CD Pipeline
on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Run Ruff
      uses: astral-sh/ruff-action@v1
      with:
        args: check --output-format=github .

  test:
    needs: lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true
    - name: Install dependencies
      run: poetry install --no-interaction
    - name: Run unit tests
      run: poetry run pytest --cov=./

  deploy:
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
    - uses: actions/checkout@v2
    - name: Google Auth
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'
    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v0'
    - name: Build and Push Container
      run: |
        gcloud builds submit --tag gcr.io/${{ secrets.PROJECT_ID }}/fastapi-app
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy fastapi-service \
          --image gcr.io/${{ secrets.PROJECT_ID }}/fastapi-app \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated
